---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 5m
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: grafana
      version: "8.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: grafana
      interval: 5m
  releaseName: grafana
  values:
    persistence:
      enabled: true
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        cert-manager.io/cluster-issuer: internal-ca
      hosts:
        - grafana.k8s.example.internal
      tls:
        - secretName: grafana-server-tls
          hosts:
            - grafana.k8s.example.internal
# Retrieve admin password with:
# kubectl get secret --namespace grafana grafana -o jsonpath="{.data.admin-password}" | base64 --decode
