apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - metrics-server.yaml
  - traefik.yaml
  - cert-manager.yaml
  - prometheus-stack.yaml
  - vault.yaml
  - secrets-store-csi-driver.yaml
